### ISSUE TITLE
Automatically update collection when open a new pack?

### ISSUE THREAD

**Issue by Ansem93** [ko-vasilev/Hearthstone-Collection-Tracker#64] opened 2016-01-16 11:44 UTC
IT's possible to update the collection when I open a new pack?

**Comment by riQQ** [comment] 2016-01-16 15:41
Right now, the pack opening isn't logged anymore. Blizzard broke this some time ago. We can only hope they fix it. Then the implementation in pull request #34 will update your collection automatically.

**Comment by culinko** [comment] 2016-02-27 16:03
Also, this issue is just dupe of #24.

**Comment by ko-vasilev** [comment] 2016-02-29 05:21
Yep, had plans on this but Blizz decided to disable ability to clearly track your pack openings.

**Closed as completed by ko-vasilev** 2016-02-29 05:21 UTC
Labels: duplicate, enhancement, wontfix
