### ISSUE TITLE
Mass dispel imports as gold

### ISSUE THREAD

**Issue by razko** [ko-vasilev/Hearthstone-Collection-Tracker#32] opened 2015-09-03 20:37 UTC
I have 1x Mass Dispel card (non-gold), and every time I import collection, it imports it as a golden card. I've tried to do this twice on fresh profiles, once with fast speed, once with normal, and both times I got the same result.

**Comment by ko-vasilev** [comment] 2015-09-04 02:12
Yes, it is a known issue with importing some of Priest cards.

**Comment by ko-vasilev** [comment] 2015-09-07 02:18
Duplicate of #26

**Closed as completed by ko-vasilev** 2015-09-07 02:18 UTC
